In [3]:
#Task 1
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]] ,dtype=float)
print(arr)
print(arr.astype(bool))

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [4]:
#Task 2
import numpy as np
a=np.array([1,2,3,4,5])
b=np.insert(a,2,55,axis=0) 
print(b)

[ 1  2 55  3  4  5]


In [5]:
#Task 3
import numpy as np
arr=np.arange(0,101,2)
print(arr)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [8]:
#Task 4
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
c=np.dot(a,b)
print(c)

55


In [14]:
#Task 5
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
num=int(input("Enter a number"))
if num in arr:
    print("The number",+num, "is present in the array:",+arr)
else:
    print("The number",+num, "is not present in the array:",+arr)

[1 2 3 4 5]


Enter a number 8


The number 8 is not present in the array: [1 2 3 4 5]
